### ISSUE TITLE
Review technical debt in repo and determine nearterm improvements

### ISSUE THREAD

**Issue by izgeri** [cyberark/terraform-provider-conjur#45]
Review this repo:
- [ ] Determine whether improvements can be made to update/modernize the release process
- [ ] Review README and CONTRIBUTING to determine if either documentation set is missing important information
- [ ] Determine if automated test suite should be augmented to alert maintainer team to possible breakages earlier
- [ ] Determine what sorts of standard maintenance tasks this repo requires. Does it need regular review to update the Terraform version used in the integration tests? Are there other dependencies (eg Golang?) that should be updated at regular intervals? 
- [ ] Determine whether any additional updates should be slated for work soon, including potential feature requests logged in GitHub issues (for small changes, we can work into backlog - for larger changes that take greater than one standard 2-3 day PR cycle, we will raise with PM)

The output of this spike will be a list of items for each category above listed in a comment on this issue, and linking to the GitHub issues for each item.

**Comment by sgnn7** [comment]
Things that need fixing in the order of importance:
- [ ] Many variables cannot be set in the `.tf` files (_unverified_) (#29)
- [ ] Code is linking to old conjur-authenticator golang code
- [ ] Goreleaser creates bad `brew` recipe links (#47)
- [ ] Documentation is pretty crude and is making up for some suboptimal deployment patterns
- [ ] Version of the plugin is missing (#30)
- [ ] Stale golang modules
- [ ] No good way to notice issues with terraform dependencies upstream
- [ ] Build infra is moderately out of date (gitlab config, no GH actions, no auto-release, etc)
- [ ] No instructions for Windows deployment and no Windows examples
- [ ] EE tests use cuke-master base image
- [ ] OSS tests use ancient container config
- [ ] Tests are overly complicated
- [ ] Various misc documentation cleanups

**Comment by izgeri** [comment]
Organizing these improvements into the categories I listed above (which is my draft of what we'll use for all of these projects):

## Improvements to release process
- Goreleaser creates bad brew recipe links (#47)

## Repo documentation improvements
- Documentation is pretty crude and is making up for some suboptimal deployment patterns (#49)
- No instructions for Windows deployment and no Windows examples (#53)
- Various misc documentation cleanups (#49)

## Test suite improvements (in particular, tests to add to alert us early to breakages)
- No good way to notice issues with terraform dependencies upstream (#51)
-  Build infra is moderately out of date (gitlab config, no GH actions, no auto-release, etc) (#52)
- EE tests use cuke-master base image (#54)
- OSS tests use ancient container config (#54)

## Repo standard maintenance tasks
-  Stale golang modules (#50)

## Enhancement requests to consider
- Version of the plugin is missing (#30)

## Bugs
- Many variables cannot be set in the .tf files (unverified) (#29)


Thanks @sgnn7 for gathering this info :)

**Comment by sgnn7** [comment]
> can you also please comment here whether updating golang modules / updating terraform or conjur/DAP versions in tests is part of required regular maintenance?

yes - this should be done when needed. we depend on both conjur-api-go and terraform modules so updates there will require us to ensure that we are up to date with them otherwise we will risk having a broken release.

**Comment by sgnn7** [comment]
Updated the list and crossed out any currently-released fixes

**Comment by izgeri** [comment]
Thanks @sgnn7! I think this issue can be closed for now, we can keep it as a record of our evaluation but all follow-up issues have been logged now.
