### ISSUE TITLE
Terraform has a Conjur Provider

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/terraform-provider-conjur#9]
ETA for completion of this epic: 2018-09-21
Confidence level of ETA accuracy: High

## Context

HashiCorp's [Terraform](https://www.terraform.io/) is a widely-used tool used to manage infrastructure as code. Terraform manifests are written in [HCL](https://www.terraform.io/docs/configuration/syntax.html).

Terraform is extendable with [providers](https://www.terraform.io/docs/providers/index.html), which can declare their own resources. A Conjur provider does not yet exist. Secrets are often needed in Terraform manifests, so being able to fetch them from Conjur improves the security stance of Terraform.

### Current Capabilities
It is currently possible to fetch secrets from Conjur within Terraform by injecting them via environment variables.  This requires the use of `summon` and specially named environment variables.  While this is possible, the goal of creating a Conjur provider is to provide a better experience.

In order to use `summon` + environment variables, the user running `terraform` must already be authenticated with Conjur.

Terraform's [`TF_VAR_name` syntax](https://www.terraform.io/docs/configuration/environment-variables.html#tf_var_name) allows a user to set Terraform variables via environment variables. To use Terraform with Summon, prefix the environment variable names in secrets.yml with `TF_VAR_`.

**secrets.yml**

```
TF_VAR_access_key: !var aws/dev/sys_powerful/access_key_id
TF_VAR_secret_key: !var aws/dev/sys_powerful/secret_access_key
```

**variables.tf**

```
variable "access_key" {} /* Variable pulled from TF_VAR_access_key environment variable */
variable "secret_key" {} /* Variable pulled from TF_VAR_secret_key environment variable */
```

Run Terraform with Summon:

```
summon terraform apply
```

## Objective

Provide a Terraform `conjur` provider with a `conjur_secret` resource that can be used to fetch secrets from a configured Conjur v5 instance.

We should also instruct customers on how to use rotation (and possible encryption) to handle [exposed secrets in plan files](https://github.com/hashicorp/terraform/issues/516).

### Initial support
When using Terraform, credentials will be able to be pulled out of Conjur.

This should mirror what HC currently implements as part of their Vault provider.  Our provider will leverage rotation to remove credentials exposed.

- https://github.com/hashicorp/terraform/issues/516
- https://www.terraform.io/docs/extend/writing-custom-providers.html
- https://github.com/terraform-providers/terraform-provider-vault

### Terraform Provider Configuration
Prerequisite is a setup and configured Conjur instance.  In order to configure the Terraform provider,  configuration values can be included in the Terraform manifest, or can be loaded using the standard Conjur client configuration mechanisms (e.g. `~/.conjurrc`, environment variables, etc). Values specified in the configuration file take precedence over other values.

#### Policy For Examples
<insert policy file contents here>

#### Terraform Manifest Provider Configuration
```
provider "conjur" {
  appliance_url = "http://localhost:8080" /* The Conjur appliance URL */
  account = "quick-start" /* The Conjur account */
  login = "admin" /* The Conjur authn login */
  api_key = "3ahcddy39rcxzh3ggac4cwk3j2r8pqwdg33059y835ys2rh2kzs2a" /* The Conjur authn API key */
  ssl_cert_path = "/etc/conjur.pem" /* The Conjur certificate file */
}
```

#### Environment Variable Provider Configuration
```
export CONJUR_APPLIANCE_URL="https://localhost:8080"
export CONJUR_ACCOUNT="quick-start"
export CONJUR_AUTHN_LOGIN="admin"
export CONJUR_AUTHN_API_KEY="3ahcddy39rcxzh3ggac4cwk3j2r8pqwdg33059y835ys2rh2kzs2a"
export CONJUR_CERT_FILE="/etc/conjur.pem"
```

And then within the Terraform manifest:

```
provider "conjur" {}
```

### Fetching Secrets Within Terraform
Secrets are dynamically fetched from the Conjur service and injected as variables into the Terraform manifest when used.  They need to be defined within the Terraform manifest prior to use.

#### Declaring Conjur Sourced Variables
The variables need to be declared prior to use.  They are declared like any other data variable with Terraform, using the path within Conjur for the name.

```
data "conjur_secret" "dbpass" {
  name = "path/to/secret" /* The Conjur secret to fetch */
}
```

#### Using Variables
The data for the variable is extracted into data.<declared_path>.<declared_name>.value.  This can be then tied to a Terraform output in order to be used.  The 'sensitive' declaration of true will prevent the value from being printed to the console, but will not prevent it from showing up in .plan files or logs.

```
output "dbpass_output" {
  value = "${data.conjur_secret.dbpass.value}" /* Extract the value from the declared variable */
  sensitive = true  /* Whether to log the value to the console when running */
}
```

### Full Terraform Manifest example
**main.tf**

```
provider "conjur" {
  appliance_url = "http://localhost:8080" /* The Conjur appliance URL */
  account = "quick-start" /* The Conjur account */
  login = "admin" /* The Conjur authn login */
  api_key = "3ahcddy39rcxzh3ggac4cwk3j2r8pqwdg33059y835ys2rh2kzs2a" /* The Conjur authn API key */
  ssl_cert_path = "/etc/conjur.pem" /* The Conjur certificate file */
}

data "conjur_secret" "dbpass" {
  name = "path/to/secret" /* The Conjur secret to fetch */
}

output "dbpass_output" {
  value = "${data.conjur_secret.dbpass.value}" /* Extract the value from the declared variable */
  sensitive = true  /* Whether to log the value to the console when running */
}

```

## Additional Notes
* If any of the provided credentials change and are needed in any resources, `terraform apply` needs to be run so that the secrets are available.

---

- [x] Test Conjur v5 Enterprise w/ Jenkins pipeline - parent of #2
- [x] Add homebrew release - parent of #3
- [x] Document summon + terraform flow - parent of #4
- [x] Use a better, more interesting test policy - parent of #5
- [x] Is there a way to avoid the secrets ending up in state files? - parent of #6 (closed)
- [x] Document how to install this provider - parent of #11
- [x] The provider uses the API to load configuration - parent of  #12 
- [ ] A demo shows that the provider can be part of creating a Rails app - parent of  #13
- [x] Provider should be documented on conjur.org - parent of #19
- [x] README is missing Authentication and Policy sections - parent of #20 

_Copied from original issue: conjurinc/appliance#262_

**Comment by jvanderhoof** [comment]
_From @jtuttle on August 2, 2018 20:9_

Tasks
- document using Summon to populate values in TF_VAR (low)
- figure out solution to secrets ending up in plan file (medium)
- spike on creating a terraform plugin (low)
- implement terraform plugin (medium / high)

**Comment by apotterri** [comment]
Having worked with the provider some, I think we should consider changing how it gets configured. Instead of duplicating the way `conjur-api-go` reads the environment, we should just let it load the configuration. The provider would do this by calling `conjurapi.LoadConfig`.

Once the API has populated a `conjurapi.Config` as much as it can, the values in the Terraform manifest should be applied to that config.
